// This file was autogenerated in src/version_git.sh
char *git_commit = "02d8d7b2cf17a3e14b7688ec9e490434ff7b21ad";
char *git_commit_short = "02d8d7b2cf*";
char *git_branch = "precompile-native-dev2";
int git_build_number = 481;
char *git_date_string = "2019-11-14 21:31 UTC";
int git_tagged_commit = 0;
int git_fork_master_distance = 58;
float git_fork_master_timestamp = 1572647428;
