// This file was autogenerated in src/version_git.sh
char *git_commit = "0af2dbcbbaa30bd60078a69b47c062639fa0a9d0";
char *git_commit_short = "0af2dbcbba*";
char *git_branch = "precompile-native-dev2";
int git_build_number = 449;
char *git_date_string = "2019-11-08 05:15 UTC";
int git_tagged_commit = 0;
int git_fork_master_distance = 338;
float git_fork_master_timestamp = 1568194482;
