// This file was autogenerated in src/version_git.sh
char *git_commit = "325eca3aa4970755dce0107eec494e05736e8e85";
char *git_commit_short = "325eca3aa4*";
char *git_branch = "precompile-native-dev2";
int git_build_number = 451;
char *git_date_string = "2019-11-13 05:11 UTC";
int git_tagged_commit = 0;
int git_fork_master_distance = 340;
float git_fork_master_timestamp = 1568194482;
